// <auto-generated />
using System;
using Launcher.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Launcher.DAL.Migrations
{
    [DbContext(typeof(LauncherDbContext))]
    [Migration("20260304181302_AddPlatforms")]
    partial class AddPlatforms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Launcher.DAL.Entities.AchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(505)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameTitleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameTitleId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GameTitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PegiRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("GameTitles");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GameTitleGenreEntity", b =>
                {
                    b.Property<Guid>("GameTitleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameTitleId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameTitleGenres");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GameTitlePlatformEntity", b =>
                {
                    b.Property<Guid>("GameTitleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameTitleId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GameTitlePlatforms");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.LibraryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.LibraryTitleEntity", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameTitleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceCentsAtPurchase")
                        .HasColumnType("INTEGER");

                    b.HasKey("LibraryId", "GameTitleId");

                    b.HasIndex("GameTitleId");

                    b.ToTable("LibraryTitles");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.PlatformEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.ReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameTitleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTitleId");

                    b.HasIndex("UserId", "GameTitleId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.UserAchievementEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.AchievementEntity", b =>
                {
                    b.HasOne("Launcher.DAL.Entities.GameTitleEntity", "GameTitle")
                        .WithMany("Achievements")
                        .HasForeignKey("GameTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTitle");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GameTitleGenreEntity", b =>
                {
                    b.HasOne("Launcher.DAL.Entities.GameTitleEntity", "GameTitle")
                        .WithMany("GameTitleGenres")
                        .HasForeignKey("GameTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launcher.DAL.Entities.GenreEntity", "Genre")
                        .WithMany("GamesTitleGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTitle");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GameTitlePlatformEntity", b =>
                {
                    b.HasOne("Launcher.DAL.Entities.GameTitleEntity", "GameTitle")
                        .WithMany("GameTitlePlatforms")
                        .HasForeignKey("GameTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launcher.DAL.Entities.PlatformEntity", "Platform")
                        .WithMany("GameTitlePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTitle");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.LibraryEntity", b =>
                {
                    b.HasOne("Launcher.DAL.Entities.UserEntity", "User")
                        .WithMany("Libraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.LibraryTitleEntity", b =>
                {
                    b.HasOne("Launcher.DAL.Entities.GameTitleEntity", "GameTitle")
                        .WithMany("LibraryTitles")
                        .HasForeignKey("GameTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launcher.DAL.Entities.LibraryEntity", "Library")
                        .WithMany("LibraryTitles")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTitle");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.ReviewEntity", b =>
                {
                    b.HasOne("Launcher.DAL.Entities.GameTitleEntity", "GameTitle")
                        .WithMany("Reviews")
                        .HasForeignKey("GameTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launcher.DAL.Entities.UserEntity", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTitle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.UserAchievementEntity", b =>
                {
                    b.HasOne("Launcher.DAL.Entities.AchievementEntity", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launcher.DAL.Entities.UserEntity", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.AchievementEntity", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GameTitleEntity", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("GameTitleGenres");

                    b.Navigation("GameTitlePlatforms");

                    b.Navigation("LibraryTitles");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.GenreEntity", b =>
                {
                    b.Navigation("GamesTitleGenres");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.LibraryEntity", b =>
                {
                    b.Navigation("LibraryTitles");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.PlatformEntity", b =>
                {
                    b.Navigation("GameTitlePlatforms");
                });

            modelBuilder.Entity("Launcher.DAL.Entities.UserEntity", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("Reviews");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
